name: Test JavaScript package

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 設定環境
        uses: actions/checkout@v2

      - name: 使用 Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: 安裝套件
        working-directory: ./js
        run: npm install

      - name: Test
        working-directory: ./js
        run: npm run test:coverage
